CREATE TABLE CUSTOMER_SALES_PRODUCTS as
SELECT
    TBL_C.CUSTOMER_ID,
    TBL_C.CUSTOMER_NAME,
    TBL_C.PRODUCT_ID,
    TBL_P.PRODUCT_DESCRIPTION
FROM
    CUSTOMER_NAMED_SALES AS TBL_C
INNER JOIN
    PRODUCTS AS TBL_P
ON
    TBL_P.PRODUCT_ID=TBL_C.PRODUCT_ID_A;
